baseURL = "https://geeklandlinux.github.io/"
languageCode = "es-es"
title = "Geekland"
theme = "PaperMod"
defaultContentLanguage = "es"
enableEmoji = true

[params]
  description = "Blog sobre tecnología, Linux, privacidad y software libre"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  env = "production"

# Icono del sitio / Favicon para navegadores
[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon.ico"
  favicon32x32 = "/favicon.ico"

# Etiqueta de la barra de navegación superior (Logo)
[params.label]
  text = "Geekland"
  icon = "/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Artículos"
    url = "/posts/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "Categorías"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 3
