baseURL = "https://geeklandlinux.github.io/"
languageCode = "es-es"
title = "Geekland"
theme = "PaperMod"
defaultContentLanguage = "es"
enableEmoji = true

[params]
  description = "Blog sobre tecnología, Linux, privacidad y software libre"
  ShowReadingTime = true
  env = "production"
  schema = true

[params.label]
  text = "Geekland"
  icon = "/favicon.ico" # Ruta a tu favicon en la carpeta static/

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Artículos"
    url = "/posts/"
    weight = 1